### ISSUE TITLE
Edit Cohort type – caption should be “Edit Cohort type”

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#23] opened 2016-08-03 07:02 UTC
Edit Cohort type – caption should be “Edit Cohort type” (High).

![capture](https://cloud.githubusercontent.com/assets/20788534/17356637/09cd2b72-5972-11e6-9c5c-496838da2386.PNG)

**Comment by cafootitt** [comment] 2016-08-03 07:19
Duplicate of https://github.com/OpenSRP/openmrs-module-cohort/issues/7 ??

**Comment by bholagabbar** [comment] 2016-08-06 19:58
Fixed in https://github.com/OpenSRP/openmrs-module-cohort/commit/e6a8018b2d1a751ed5e7623b67c9c0e9bfb9d003

**Closed as completed** 2016-08-19 06:37 UTC
Labels: bug, resolved
